### ISSUE TITLE
Merge with Pandas?

### ISSUE THREAD

**Issue by petebachant** [HHammond/PrettyPandas#36]
This looks awesome. Have you tried submitting a PR to include in Pandas?

**Comment by HHammond** [comment]
I haven't tried submitting it to Pandas, but some of the team there have seen this during PR's I've put in for their style API. I'm not sure how I feel about it being included in Pandas at this time. 

The styling here just CSS and the Styler class from Pandas. I think that there will always be room for additional CSS styling libraries so that people can decorate their reports and tables in whatever ways they want. It would be neat to have a few different CSS options built-in though.

I would like to see something like the summaries API in Pandas proper, but I don't know where it fits. I don't think that it's something in their roadmap, but I also haven't pitched adding summaries to Pandas either.
